### ISSUE TITLE
About the Vocabulary

### ISSUE THREAD

**Issue by ZiyuFanCSU** [zjunlp/MolGen#10]
I would like to ask, are the vocabularies used in NP dataset and synthetic dataset the same, that is, in the second stage of pre-training mentioned in the paper, but the Nature products are much longer than the synthetic? Can you tell me what sequence length you set for the encoder?

**Comment by tszslovewanpu** [comment]
词汇表一致吧，因为元素是一样的啊，只是序列长了

**Comment by Fangyinfff** [comment]
Yes, just as @tszslovewanpu mentioned, the vocabularies used in the NP dataset and the synthetic dataset are consistent because the elements used are the same, which are the smallest units that make up the molecular sequences. If there is sufficient GPU memory available, the max sequence length can be set to 436 or higher. In other cases, it can be set to around 400.

<img width="495" alt="image" src="https://github.com/zjunlp/MolGen/assets/61076726/2636e654-43af-4414-a4e4-10e82a973c5c">

**Comment by ZiyuFanCSU** [comment]
> Yes, just as @tszslovewanpu mentioned, the vocabularies used in the NP dataset and the synthetic dataset are consistent because the elements used are the same, which are the smallest units that make up the molecular sequences. If there is sufficient GPU memory available, the max sequence length can be set to 436 or higher. In other cases, it can be set to around 400.
> 
> <img alt="image" width="495" src="https://private-user-images.githubusercontent.com/61076726/313938096-2636e654-43af-4414-a4e4-10e82a973c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjg3NDgsIm5iZiI6MTcxMDgyODQ0OCwicGF0aCI6Ii82MTA3NjcyNi8zMTM5MzgwOTYtMjYzNmU2NTQtNDNhZi00NDE0LWE0ZTQtMTBlODJhOTczYzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYjg0MjkxMTBiNDlhNWZjYzc3MDVkYTEyZDgyYWRhNTRkYjdkODA4YmEzODAyZTk0ZTI3MTFkNWY2NDBkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ps7Rsb9NS4ogv0po5wuoTxgXGDtAbaFZSxWKBAGqcvU">

Thank you for your reply. I was just thinking about the GPU issue and thought you used some segmentation techniques when dealing with NP.
